import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
// import styles from '../styles/Home.module.css'

const Blogs: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Simply Jet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <h1>Blogs Page</h1>
      <Footer />
      
    </div>
  )
}

export default Blogs
